# Generated by Django 5.1.2 on 2024-10-28 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField()),
                ('remaining_points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point_exchange_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pointexchangetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
