# Generated by Django 5.1.2 on 2024-10-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_changepoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
