# Generated by Django 5.1.2 on 2024-12-05 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_address_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.polloption'),
        ),
        migrations.CreateModel(
            name='PollSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('poll_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pollcategory')),
            ],
        ),
    ]
